### ISSUE TITLE
Add the documentation for make traefik auto redirect to https

### ISSUE THREAD

**Issue by yodatak** [k3s-io/docs#160]
Aswome job  for make kubernetes easier to all 
I want to be able to find easy on k3s documentation how to auto redirect to https with traefik without modifing manifest 

Like this way 
`kubectl apply -f httpstraefik.yaml`
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      websecure:
        tls:
          enabled: true
      web:
        redirectTo: websecure
```

Its a common issue why people don't use the bundled traefik because they can't find how to make http to https redirection 

Like we see in some forums 
https://stackoverflow.com/questions/68575472/k3s-redirect-http-to-https/71989847#71989847

**Comment by joshuacox** [comment]
this seems to still be aproblem, why doesn't redirect by default?

And although I have added this:

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
```

and a line like:

```
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd
```

but still no enforcement.

**Comment by brandond** [comment]
> why doesn't it redirect by default?

Because most people don't want that? 

You can find chart values here: https://github.com/traefik/traefik-helm-chart/blob/v27.0.2/traefik/values.yaml#L658-L663

Note that you should match values.yaml structure to the correct version of the chart for whatever release of K3s you're using.

**Comment by brandond** [comment]
It's not clear to me what redirecting http to https has to do with how you transmit credentials. Traefik is documented extensively on the Traefik website; our docs provide examples of customizing the chart, and links to the values and upstream docs if you need to dig further.

I'm locking this, as we are not interested in changing the default behavior of Traefik's insecure entrypoint.

**Comment by joshuacox** [comment]
for all the people ending up here wading through all the broken and plain wrong examples across the internet here is the working yaml:

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      websecure:
        tls:
          enabled: true
      web:
        redirectTo: 
          port: websecure
          priority: 10
```
