### ISSUE TITLE
questions on k3s hardening

### ISSUE THREAD

**Issue by cwrx777** [k3s-io/docs#306]
Related issue: 
[Previous conversation](https://github.com/k3s-io/k3s/discussions/10458#discussioncomment-9990502) in k3s-io/k3s#10458

Hi @dereknola Thank you for answering my questions. I have additoinal questions.

> Yes, this check is outdated, as the rotate feature gate has been "on by default" since Kubernetes 1.11. This check is basically just "did you do something stupid and turn off the security feature".

how do I audit that `RotateKubeletServerCertificate` feature is enabled? 

Additional questions:

- [1.1.13](https://docs.k3s.io/security/self-assessment-1.8#1113-ensure-that-the-adminconf-file-permissions-are-set-to-600-or-more-restrictive-automated)
  why is this `Not Applicable` ? isn't it just changing the file permission to 600?

My worker node is run using the following `config.yaml`:
```yaml
...
protect-kernel-defaults: true
kubelet-arg:
  - 'streaming-connection-idle-timeout=5m'
  - 'make-iptables-util-chains=true'
```
`k3s-agent.service`:
```
ExecStart=/usr/local/bin/k3s \
    agent \
        '--config=/test/k3s/config/config.yaml' \
```

- [4.1.9](https://docs.k3s.io/security/self-assessment-1.8#419-ensure-that-the-kubelet---config-configuration-file-has-permissions-set-to-600-or-more-restrictive-automated), [4.1.10](https://docs.k3s.io/security/self-assessment-1.8#4110-ensure-that-the-kubelet---config-configuration-file-ownership-is-set-to-root-automated)
  Does [`kubelet --config configuration file`](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/#:~:text=%2D%2Dconfig%20string) refer to [`kubelet.kubeconfig`](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/#:~:text=Path%20to%20a-,kubeconfig,-file%2C%20specifying%20how)?
- [4.2.8](https://docs.k3s.io/security/self-assessment-1.8#428-ensure-that-the-eventrecordqps-argument-is-set-to-a-level-which-ensures-appropriate-event-capture-manual), [4.2.10](https://docs.k3s.io/security/self-assessment-1.8#4210-ensure-that-the---rotate-certificates-argument-is-not-set-to-false-manual), [4.2.11](https://docs.k3s.io/security/self-assessment-1.8#4211-verify-that-the-rotatekubeletservercertificate-argument-is-set-to-true-manual) 
   I am not able to verify the required parameters from the ps output. 
   ```bash
  /bin/ps -fC containerd
   UID          PID    PPID  C STIME TTY          TIME CMD
   root     3002164 3001447  0 Jul08 ?        00:06:39 containerd
   ```
- [4.2.12](https://docs.k3s.io/security/self-assessment-1.8#4212-ensure-that-the-kubelet-only-makes-use-of-strong-cryptographic-ciphers-manual) 
 Does the kubelet config refer to `/var/lib/rancher/k3s/agent/kubelet.kubeconfig `
`kubelet.kubeconfig`:
  ```
  apiVersion: v1
  clusters:
  - cluster:
      server: https://127.0.0.1:6444
      certificate-authority: /var/lib/rancher/k3s/agent/server-ca.crt
    name: local
  contexts:
  - context:
      cluster: local
      namespace: default
      user: user
    name: Default
  current-context: Default
  kind: Config
  preferences: {}
  users:
  - name: user
    user:
      client-certificate: /var/lib/rancher/k3s/agent/client-kubelet.crt
      client-key: /var/lib/rancher/k3s/agent/client-kubelet.key
  ```
- [4.2.1.3](https://docs.k3s.io/security/self-assessment-1.8#4213-ensure-that-a-limit-is-set-on-pod-pids-manual)
  Where is `pod-pids` supposed to be set? I dont see that this is set in the kubelet CLI arguments. 
   ```bash
    Running kubelet 
  --address=0.0.0.0 
  --allowed-unsafe-sysctls=net.ipv4.ip_forward,net.ipv6.conf.all.forwarding 
  --anonymous-auth=false 
  --authentication-token-webhook=true 
  --authorization-mode=Webhook 
  --cgroup-driver=systemd 
  --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt 
  --cloud-provider=external 
  --cluster-dns=10.43.0.10 
  --cluster-domain=cluster.local 
  --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock 
  --containerd=/run/k3s/containerd/containerd.sock 
  --eviction-hard=imagefs.available<5%,nodefs.available<5% 
  --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% 
  --fail-swap-on=false 
  --feature-gates=CloudDualStackNodeIPs=true 
  --healthz-bind-address=127.0.0.1 
  --hostname-override=skhromivpapp03.shses.shs.com.sg 
  --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig 
  --make-iptables-util-chains=true 
  --node-ip=10.236.49.161 
  --node-labels=node-type=worker 
  --pod-infra-container-image=rancher/mirrored-pause:3.6 
  --pod-manifest-path=/var/lib/rancher/k3s/agent/pod-manifests 
  --protect-kernel-defaults=true 
  --read-only-port=0 
  --resolv-conf=/etc/resolv.conf 
  --serialize-image-pulls=false 
  --streaming-connection-idle-timeout=5m 
  --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt 
  --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key
     ```
